<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<xsl:stylesheet version="2.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
		<head>
			<title>XML Sitemap</title>
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
			<style type="text/css">
				body {
					font-family: Helvetica, Arial, sans-serif;
					font-size: 13px;
					color: #545353;
					background-color: #ffffff;
					margin: 0;
					padding: 20px 0;
				}
				table {
					border: none;
					border-collapse: collapse;
					width: 100%;
				}
				#sitemap tr:nth-child(odd) td {
					background-color: #eee !important;
				}
				#sitemap tbody tr:hover td {
					background-color: #ccc;
				}
				#sitemap tbody tr:hover td, #sitemap tbody tr:hover td a {
					color: #000;
				}
				#content {
					margin: 0 auto;
					width: 1000px;
					max-width: 95%;
				}
				.expl {
					margin: 18px 3px;
					line-height: 1.4em;
				}
				.expl a {
					color: #da3114;
					font-weight: 600;
					text-decoration: none;
				}
				.expl a:visited {
					color: #da3114;
				}
				.expl a:hover {
					text-decoration: underline;
				}
				a {
					color: #000;
					text-decoration: none;
				}
				a:visited {
					color: #777;
				}
				a:hover {
					text-decoration: underline;
				}
				td {
					font-size: 11px;
					padding: 6px 10px;
					vertical-align: middle;
				}
				th {
					text-align: left;
					padding: 6px 10px;
					font-size: 11px;
					font-weight: bold;
				}
				thead th {
					border-bottom: 1px solid #000;
				}
				.search-box {
					margin: 15px 0;
				}
				.search-input {
					padding: 6px 10px;
					font-size: 12px;
					border: 1px solid #ccc;
					border-radius: 3px;
					width: 300px;
					outline: none;
					font-family: Helvetica, Arial, sans-serif;
				}
				.search-input:focus {
					border-color: #da3114;
				}
			</style>
			<script type="text/javascript">
				function filterSitemap() {
					var input = document.getElementById('sitemap-search');
					var filter = input.value.toLowerCase();
					var tbody = document.getElementById('sitemap-tbody');
					if (!tbody) return;
					var rows = tbody.getElementsByTagName('tr');

					for (var i = 0; i &lt; rows.length; i++) {
						var text = rows[i].textContent || rows[i].innerText;
						if (text.toLowerCase().indexOf(filter) &gt; -1) {
							rows[i].style.display = "";
						} else {
							rows[i].style.display = "none";
						}
					}
				}
			</script>
		</head>
		<body>
		<div id="content">
			<h1>XML Sitemap</h1>
			<p class="expl">
				Generated by CTI CMS, this is an XML Sitemap, meant for consumption by search engines.<br/>
				You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank" rel="noopener">sitemaps.org</a>.
			</p>
			
			<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
				<p class="expl">
					This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.
				</p>
				<div class="search-box">
					<input type="text" id="sitemap-search" class="search-input" onkeyup="filterSitemap()" placeholder="Filter sitemaps..." />
				</div>
				<table id="sitemap" cellpadding="3">
					<thead>
					<tr>
						<th width="75%">Sitemap</th>
						<th width="25%">Last Modified</th>
					</tr>
					</thead>
					<tbody id="sitemap-tbody">
					<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
						<xsl:variable name="sitemapURL">
							<xsl:value-of select="sitemap:loc"/>
						</xsl:variable>
						<tr>
							<td>
								<a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
							</td>
							<td>
								<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
							</td>
						</tr>
					</xsl:for-each>
					</tbody>
				</table>
			</xsl:if>

			<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
				<p class="expl">
					This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
				</p>
				<div class="search-box">
					<input type="text" id="sitemap-search" class="search-input" onkeyup="filterSitemap()" placeholder="Filter URLs..." />
				</div>
				<table id="sitemap" cellpadding="3">
					<thead>
					<tr>
						<th width="80%">URL</th>
						<th width="5%">Images</th>
						<th title="Last Modification Time" width="15%">Last Mod.</th>
					</tr>
					</thead>
					<tbody id="sitemap-tbody">
					<xsl:for-each select="sitemap:urlset/sitemap:url">
						<tr>
							<td>
								<xsl:variable name="itemURL">
									<xsl:value-of select="sitemap:loc"/>
								</xsl:variable>
								<a href="{$itemURL}">
									<xsl:value-of select="sitemap:loc"/>
								</a>
							</td>
							<td>
								<xsl:value-of select="count(image:image)"/>
							</td>
							<td>
								<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
							</td>
						</tr>
					</xsl:for-each>
					</tbody>
				</table>
			</xsl:if>
		</div>
		</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
